### ISSUE TITLE
Arbitrary tag limit?

### ISSUE THREAD

**Issue by Jdbaii** [NoppesTheFolf/E621Client#14]
The library appears to be hardcoded to only accept up to 6 tags in searches, but this does not seem to be an official API limitation. In fact, the API docs state "Any tag combination that works on the website will work here." and the website certainly does allow more than 6 tags. Is this limit arbitrary or am I missing something?

**Comment by NoppesTheFolf** [comment]
Hey there! Thanks for bringing this to my attention. I'm fairly certain that when E621Client got written the limit on the number of tags that could be searched through was 6 on the website as well. I did some testing of my own this week and determined that the upper limit has been increased to 40 since then. I've updated the library and you can now [download a newer version of E621Client (0.8.1)](https://www.nuget.org/packages/Noppes.E621Client/0.8.1) with the updated constraints.
