### ISSUE TITLE
Add support for score_cutoff in IQDB searches

### ISSUE THREAD

**Issue by Jdbaii** [NoppesTheFolf/E621Client#15]
E621 allows you to set this when doing an IQDB search on their site, in my testing so far it seems like a value >= 80 means some correct matches are not returned. A value below 60 definitely returns some false positives. Around 75 seems to be a good value. The default when nothing is specified seems to be higher (90?) so some correct matches would not be returned. So being able to specify the cutoff would be quite useful.
![image](https://github.com/NoppesTheFolf/E621Client/assets/1253406/1a6b93fd-89ca-466f-867e-7e87fec75e35)

**Comment by NoppesTheFolf** [comment]
Hi there again, just as with the [issue about the tags search limit](https://github.com/NoppesTheFolf/E621Client/issues/14), very likely another case of e621 having updated their API since E621Client's IQDB wrapper code got written.

I've updated E621Client to allow for the similarity cutoff score to be passed to the API. [Version 0.8.2](https://www.nuget.org/packages/Noppes.E621Client/0.8.2) just got released that contains the functionality.

Thanks for having created an issue for it!
